# Generated by Django 3.2.6 on 2022-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('time', models.TimeField()),
                ('img', models.ImageField(default=None, upload_to=None)),
            ],
        ),
    ]
