# Generated by Django 3.2.6 on 2022-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='img',
        ),
    ]
