# Generated by Django 3.2.6 on 2022-01-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0005_alter_notes_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='img',
        ),
    ]
